### ISSUE TITLE
How to configure multiple custom discovery handlers?

### ISSUE THREAD

**Issue by mregen** [project-akri/akri#566]
**Describe the bug**

The custom resource definition for Akri has only one `custom` entry for a custom discovery handler. Is it possible to 
i) add multiple custom discovery handler?
ii) run the same custom discovery handler with different configuration in multiple pods?

**Expected behavior**

Support to add multiple custom discovery handlers for different device types or run multiple identical discovery handlers with different discoveryDetails.

**Comment by harrison-tin** [comment]
Hi @mregen, this is most likely a document issue. When we configurate the custom discovery handler in the helm chart, `custom` is just a name that we give to the discovery handler. Giving a different name other than `custom` should be able to solve this problem.

**Comment by mregen** [comment]
Hi @harrison-tin, there is only a definition in the CRD for `custom`, so when I add a second definition for e.g. `custom2`  it is simply ignored after the helm update. 
Switching between custom/custom2 shows me after helm update that only the discovery handler named `custom` is activated, the other is ignored. 

e.g. see here:

```yaml
kubernetesDistro: k8s

custom:
  configuration:
    enabled: true
    name: akri-opcua-asset
    brokerProperties: {}
    discoveryHandlerName: opcua-asset
    discoveryDetails: |
      opcuaDiscoveryMethod:
        asset:
          endpointUrl: "opc.tcp://***redacted***"
          useSecurity: false          
          autoAcceptUntrustedCertificates: true

  discovery:
    enabled: true
    name: akri-opcua-asset-discovery
    image:
      repository: ***redacted***
      tag: latest
      pullPolicy: Always
    useNetworkConnection: true
    port: 80
    nodeSelectors: {}
    resources:
      memoryRequest: 128Mi
      cpuRequest: 20m
      memoryLimit: 512Mi
      cpuLimit: 100m
     
custom2:
  configuration:
    enabled: true
    name: akri-opcua-asset2
    brokerProperties: {}
    capacity: 8
    discoveryHandlerName: opcua-asset2
    discoveryDetails: |
      opcuaDiscoveryMethod:
        asset:
          endpointUrl: "opc.tcp://***redacted***"
          useSecurity: false          
          autoAcceptUntrustedCertificates: true

  discovery:
    enabled: true
    name: akri-opcua-asset2-discovery
    image:
      repository: ***redacted***
      tag: latest
      pullPolicy: Always
    useNetworkConnection: true
    port: 80
    resources:
      memoryRequest: 64Mi
      cpuRequest: 10m
      memoryLimit: 512Mi
      cpuLimit: 100m
```
