### ISSUE TITLE
Helm: Enable multiple separate udev configurations 

### ISSUE THREAD

**Issue by melinda-mytra** [project-akri/akri#714]
**Is your feature request related to a way you would like Akri extended? Please describe.**
I want to apply different broker jobs to different USB device types. Currently I can only specify one `udev` configuration. If I've totally misunderstood this, please point me the right way. 

**Describe the solution you'd like**
Make configurations under `udev` an iterable, so you can generate multiple seperate named `udev` configurations from values.yaml. E.g.
```
  udev:
    discovery:
      enabled: true
    configurations:
    -   name: akri-udev-stm
        capacity: 2
        enabled: true
        brokerJob:
          image:
             repository: "broker-x"
        discoveryDetails:
          udevRules:
            - 'SUBSYSTEM=="usb", ATTR{idVendor}=="xxx", ATTR{idProduct}=="xxx"'
    -   name: akri-udev-camera
        capacity: 4
        enabled: true
        brokerJob:
          image:
             repository: "broker-y"
        discoveryDetails:
          groupRecursive: true
          udevRules:
            - 'SUBSYSTEM=="usb", ATTR{idVendor}=="yyy", ATTR{idProduct}=="yyy"'
 ```   
          

**Describe alternatives you've considered**
* Using multiple `udev` rules: This doesn't enable running different brokers by device type
* Creating my own templates for additional `udev` configurations and brokers: will try

**Additional context**
